services:
  agent-slite:
    env_file:
      - ../.env
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        CONFIG_FILE: configs/slite.agent.json
    image: agent-smith:slite
    container_name: agent-smith-slite
    environment:
      - AGENT_CONFIG_PATH=/app/config/agent.json
    ports:
      - "8081:8080"

  agent-newrelic:
    env_file:
      - ../.env
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        CONFIG_FILE: configs/newrelic.agent.json
    image: agent-smith:newrelic
    container_name: agent-smith-newrelic
    environment:
      - AGENT_CONFIG_PATH=/app/config/agent.json
    ports:
      - "8082:8080"
